### ISSUE TITLE
can't find config file

### ISSUE THREAD

**Issue by ryankimky** [loolzaaa/faster-rcnn-pytorch#1]
For run.py, i can't find config file.

Traceback (most recent call last):
  File "run.py", line 7, in <module>
    from config import cfg
ImportError: No module named 'config'

plz upload  config file. 
thx

**Comment by loolzaaa** [comment]
Config file already uploaded, [this is it](https://github.com/loolzaaa/faster-rcnn-pytorch/blob/master/lib/config.py)

Which version of python do you use? I don't have an `__init__.py` files in modules because it is not necessary for Python 3.3+

Also, there is a next code in `run.py` script:
```python
lib_path = os.path.join(os.path.dirname(__file__), 'lib')
if lib_path not in sys.path:
    sys.path.insert(0, lib_path)
```
This code add ./lib folder to sys.path, where python search modules.

**So, you can add `print(sys.path)` after code i show above and check, that ./lib folder of library was added to sys.path variable.**

**Comment by kyungyulkim** [comment]
i am using Python 3.5.2~~

**Comment by loolzaaa** [comment]
Are you check availability of ./lib folder in sys.path list after start `run` script?

**Comment by ryankimky** [comment]
i am using python 3.5.2.
i still checking the your run.py script.

**Comment by loolzaaa** [comment]
Oh, this is my mistake! You try to import config module **before** add its path to sys.

Try to change in `run.py`:
**BEFORE**:
```python
from config import cfg`
...
from utils.net_utils import parse_additional_params
```

**AFTER**:
```python
from lib.config import cfg
...
from lib.utils.net_utils import parse_additional_params
```

**Comment by ryankimky** [comment]
thx, i will try to run it again.

**Comment by loolzaaa** [comment]
I am update library with https://github.com/loolzaaa/faster-rcnn-pytorch/commit/4231d939eca754329d3912fcabb7ded62be762d1, just pull it.

Feel free to reopen issue if problem did not solved.

**Comment by ryankimky** [comment]
> I am update library with [4231d93](https://github.com/loolzaaa/faster-rcnn-pytorch/commit/4231d939eca754329d3912fcabb7ded62be762d1), just pull it.
> 
> Feel free to reopen issue if problem did not solved.

thx to fix it.

but, i already add 'lib' to all import~ :-)
